---
title: 'Estadística Avanzada: PEC1 - Preproceso'
author: "Autor: Erick Franz García Miranda"
date: "Marzo 2020"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header:
  pdf_document:
    highlight: zenburn
    toc: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, echo=T)
```


******
# Descripción del dataset
******


******
# Integración y selección
******

Primero, importaremos el dataset.

```{r echo=TRUE, message=FALSE, warning=FALSE}
#Importamos el data set
data_fifa<-read.csv("../data/terremotos_centro_sur_america.csv",header=T,sep=",")

head(data_fifa)
```


******
# Limpieza
******

##  Elementos vacios

##  Valores extremos

******
# Analisis de datos
******


##  Planificación

##  Normalidad y Homogeneidad

##  Pruebas estadísticas


******
# Gráficos y tablas de resultados
******


******
# Resolución del problema
******


******
# Código
******